### ISSUE TITLE
决策流中节点找不到的问题

### ISSUE THREAD

**Issue by lhch102** [youseries/urule#101]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.1.5

*  #### 遇到的问题详细描述：
代码中调用决策流时，报错节点找不到

*  #### 涉及到的异常信息（完整异常信息）：
客户端报错信息：
信息: Load knowledgepackage from remote...
com.bstek.urule.RuleException: Flow node [车主准入判断] not found.
	at com.bstek.urule.model.flow.FlowDefinition.getFlowNode(FlowDefinition.java:95)
	at com.bstek.urule.model.flow.FlowDefinition.buildConnectionToNode(FlowDefinition.java:84)
	at com.bstek.urule.runtime.KnowledgePackageWrapper.buildDeserialize(KnowledgePackageWrapper.java:85)
	at com.bstek.urule.model.rete.JsonUtils.parseKnowledgePackageWrapper(JsonUtils.java:122)
	at com.bstek.urule.runtime.service.RemoteServiceImpl.getKnowledge(RemoteServiceImpl.java:53)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.fetchKnowledgePackage(KnowledgeServiceImpl.java:88)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.getKnowledge(KnowledgeServiceImpl.java:52)
	at com.test.InvokeTest.doTest(InvokeTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

com.bstek.urule.RuleException: com.bstek.urule.RuleException: Flow node [车主准入判断] not found.

	at com.bstek.urule.model.rete.JsonUtils.parseKnowledgePackageWrapper(JsonUtils.java:125)
	at com.bstek.urule.runtime.service.RemoteServiceImpl.getKnowledge(RemoteServiceImpl.java:53)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.fetchKnowledgePackage(KnowledgeServiceImpl.java:88)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.getKnowledge(KnowledgeServiceImpl.java:52)
	at com.test.InvokeTest.doTest(InvokeTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.bstek.urule.RuleException: Flow node [车主准入判断] not found.
	at com.bstek.urule.model.flow.FlowDefinition.getFlowNode(FlowDefinition.java:95)
	at com.bstek.urule.model.flow.FlowDefinition.buildConnectionToNode(FlowDefinition.java:84)
	at com.bstek.urule.runtime.KnowledgePackageWrapper.buildDeserialize(KnowledgePackageWrapper.java:85)
	at com.bstek.urule.model.rete.JsonUtils.parseKnowledgePackageWrapper(JsonUtils.java:122)
	... 31 more

*  #### 相关截图：

**Comment by youseries** [comment]
附上你的流程图，详细说明你的定义方式

**Comment by lhch102** [comment]
已解决。
