### ISSUE TITLE
决策流中配置其他决策流，代码中获取节点type为null的问题

### ISSUE THREAD

**Issue by lhch102** [youseries/urule#103]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
# 2.1.5
*  #### 遇到的问题详细描述：
决策流中配置其他决策流，代码中类：FlowNodeJsonDeserializer的方法deserialize中，获取到决策流的那个节点时，JsonNode type=childNode.get("type");  type为null，导致无法继续流程
*  #### 涉及到的异常信息（完整异常信息）：
`com.bstek.urule.RuleException: Flow node [商城风控策略] not found.
	at com.bstek.urule.model.flow.FlowDefinition.getFlowNode(FlowDefinition.java:95)
	at com.bstek.urule.model.flow.FlowDefinition.buildConnectionToNode(FlowDefinition.java:84)
	at com.bstek.urule.runtime.KnowledgePackageWrapper.buildDeserialize(KnowledgePackageWrapper.java:85)
	at com.bstek.urule.model.rete.JsonUtils.parseKnowledgePackageWrapper(JsonUtils.java:122)
	at com.bstek.urule.runtime.service.RemoteServiceImpl.getKnowledge(RemoteServiceImpl.java:53)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.fetchKnowledgePackage(KnowledgeServiceImpl.java:88)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.getKnowledge(KnowledgeServiceImpl.java:52)
	at com.test.InvokeTest.doTest(InvokeTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`
*  #### 相关截图：
![image](https://user-images.githubusercontent.com/21078340/42989230-c4001ef2-8c31-11e8-9a57-3f3c6dcc5c3c.png)

**Comment by youseries** [comment]
你怎么在一个规则流里引用其它规则的？说清楚！

**Comment by lhch102** [comment]
![image](https://user-images.githubusercontent.com/21078340/43124763-af0b7dbc-8f5a-11e8-9b3e-be6378662fb6.png)



引入的决策流：
![image](https://user-images.githubusercontent.com/21078340/43124728-8eed2b7a-8f5a-11e8-908a-b94874c98b1b.png)

当执行到【商城风控策略】节点时，报错：节点找不到

**Comment by lhch102** [comment]
已解决。
