### ISSUE TITLE
与springboot集成问题

### ISSUE THREAD

**Issue by sxcooler** [youseries/urule#118]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
urule-console-pro 2.1.3
或
urule-console 2.1.7

*  #### 遇到的问题详细描述：
1. 这篇文档 http://www.bstek.com/resources/doc/17yu-springboot-ji-cheng.html 提到的jar包，下下来运行就报错（已指定repo目录），报错见下文。

2. 参考 https://github.com/youseries/urule/tree/master/urule-springboot ，尝试与已有项目集成，配好servlet、import了context，能够在console中看见uRule的banner，不报错，但就是不监控我指定的端口，netstat查不到，浏览器访问提示connection refused。

*  #### 涉及到的异常信息（完整异常信息）：
```
2019-03-05 10:43:36.752  WARN 3244 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.knowledgeBuilder' defined in class path resource [urule-core-context.xml]: Cannot resolve reference to bean 'urule.rulesRebuilder' while setting bean property 'rulesRebuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.rulesRebuilder' defined in class path resource [urule-core-context.xml]: Cannot resolve reference to bean 'urule.resourceLibraryBuilder' while setting bean property 'resourceLibraryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.resourceLibraryBuilder' defined in class path resource [urule-core-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryResourceProvider' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryService' while setting bean property 'repositoryService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryService' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryBuilder' while setting bean property 'repositoryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
2019-03-05 10:43:36.755  INFO 3244 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2019-03-05 10:43:36.762  INFO 3244 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2019-03-05 10:43:36.795  INFO 3244 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-03-05 10:43:36.829 ERROR 3244 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.knowledgeBuilder' defined in class path resource [urule-core-context.xml]: Cannot resolve reference to bean 'urule.rulesRebuilder' while setting bean property 'rulesRebuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.rulesRebuilder' defined in class path resource [urule-core-context.xml]: Cannot resolve reference to bean 'urule.resourceLibraryBuilder' while setting bean property 'resourceLibraryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.resourceLibraryBuilder' defined in class path resource [urule-core-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryResourceProvider' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryService' while setting bean property 'repositoryService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryService' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryBuilder' while setting bean property 'repositoryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1611) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1363) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at com.bstek.urule.springboot.Application.main(Application.java:15) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [urule-springboot-0.0.1-20181121.034529-4.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [urule-springboot-0.0.1-20181121.034529-4.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [urule-springboot-0.0.1-20181121.034529-4.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [urule-springboot-0.0.1-20181121.034529-4.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.rulesRebuilder' defined in class path resource [urule-core-context.xml]: Cannot resolve reference to bean 'urule.resourceLibraryBuilder' while setting bean property 'resourceLibraryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.resourceLibraryBuilder' defined in class path resource [urule-core-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryResourceProvider' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryService' while setting bean property 'repositoryService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryService' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryBuilder' while setting bean property 'repositoryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1611) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1363) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.resourceLibraryBuilder' defined in class path resource [urule-core-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryResourceProvider' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryService' while setting bean property 'repositoryService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryService' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryBuilder' while setting bean property 'repositoryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:589) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryResourceProvider' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryService' while setting bean property 'repositoryService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryService' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryBuilder' while setting bean property 'repositoryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1611) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1363) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1198) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at com.bstek.urule.builder.AbstractBuilder.setApplicationContext(AbstractBuilder.java:45) ~[urule-core-pro-2.0.9-SNAPSHOT.jar!/:na]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:120) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 43 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryService' defined in class path resource [urule-console-context.xml]: Cannot resolve reference to bean 'urule.repositoryBuilder' while setting bean property 'repositoryBuilder'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1611) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1363) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 61 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1708) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 71 common frames omitted
Caused by: com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
	at com.bstek.urule.console.repository.RepositoryBuilder.initRepositoryDir(RepositoryBuilder.java:253) ~[urule-console-pro-2.0.9-SNAPSHOT.jar!/:na]
	at com.bstek.urule.console.repository.RepositoryBuilder.afterPropertiesSet(RepositoryBuilder.java:268) ~[urule-console-pro-2.0.9-SNAPSHOT.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1767) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 78 common frames omitted
```

*  #### 相关截图：

**Comment by zhangjialiang9** [comment]
同问

**Comment by 965223108** [comment]
com.bstek.urule.exception.RuleException: Repository root dir /private/var/folders/tc/j3lzknr10bgg0cxlgctnlvcm0000gn/T/tomcat-docbase.794680516657935998.8080/Users/sxc/work/testurule/tmp is not exist.
存储目录没有设置，在配置文件中配上存储目录就好了
