### ISSUE TITLE
使用jackrabbit试配置数据库不生效

### ISSUE THREAD

**Issue by woftan** [youseries/urule#123]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.1.8-SNAPSHOT

*  #### 遇到的问题详细描述：
按操作指导使用jackrabbit方式配置数据库，urule.repository.dir属性以及urule.repository.datasourcename和urule.repository.databasetype属性也注释了，但启动报找不到urule.repository.dir，数据库配置没有生效

*  #### 涉及到的异常信息（完整异常信息）：
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'urule.repositoryBuilder' defined in class path resource [urule-console-context.xml]: Invocation of init method failed; nested exception is com.bstek.urule.exception.RuleException: You need config "urule.repository.dir" property for set repository home dir.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1708) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 43 common frames omitted
Caused by: com.bstek.urule.exception.RuleException: You need config "urule.repository.dir" property for set repository home dir.
	at com.bstek.urule.console.repository.RepositoryBuilder.afterPropertiesSet(RepositoryBuilder.java:279) ~[urule-console-pro-2.1.3.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1767) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 50 common frames omitted

*  #### 相关截图：

**Comment by lvyunxue** [comment]
在系统中 配置urule.repository.dir 的值，并在文件目录相应位置创建同名空文件夹，就ok啦

**Comment by youseries** [comment]
找不到urule.repository.dir属性，说明你的properties文件加载配置有问题，在文档 http://www.bstek.com/resources/doc/2an-zhuang-yu-pei-zhi.html 中详细介绍了properties文件的配置方式，要按文档介绍来，否则会因properties加载顺序导致属性不生效，从而出现上述问题。
