### ISSUE TITLE
使用2.1.1时点击知识库会报错，切换到2.1就不会有问题

### ISSUE THREAD

**Issue by wukonggg** [youseries/urule#14]
报错截图：

![snipaste20171211_164354](https://user-images.githubusercontent.com/10458950/33822450-8a49d84e-de92-11e7-9ad1-7378f52f70bc.png)

后台日志：
```
Using CATALINA_HOME:   "D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20"
Using CATALINA_TMPDIR: "D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20\temp"
Using JRE_HOME:        "D:\Work\Lab\bin\Java\jdk1.8.0_121"
Using CLASSPATH:       "D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20\bin\bootstrap.jar;D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20\bin\tomcat-juli.jar"
11-Dec-2017 16:41:58.837 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.20
11-Dec-2017 16:41:58.841 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 2 2017 21:35:49 UTC
11-Dec-2017 16:41:58.842 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.20.0
11-Dec-2017 16:41:58.842 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 10
11-Dec-2017 16:41:58.842 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
11-Dec-2017 16:41:58.842 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
11-Dec-2017 16:41:58.842 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             D:\Work\Lab\bin\Java\jdk1.8.0_121\jre
11-Dec-2017 16:41:58.842 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_121-b13
11-Dec-2017 16:41:58.843 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
11-Dec-2017 16:41:58.843 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         D:\Work\Lab\bin\JetBrains\data-idea\system\tomcat\Unnamed_wukong-practice-urule
11-Dec-2017 16:41:58.843 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20
11-Dec-2017 16:41:58.843 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=D:\Work\Lab\bin\JetBrains\data-idea\system\tomcat\Unnamed_wukong-practice-urule\conf\logging.properties
11-Dec-2017 16:41:58.844 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
11-Dec-2017 16:41:58.844 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote=
11-Dec-2017 16:41:58.844 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
11-Dec-2017 16:41:58.844 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=127.0.0.1
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=D:\Work\Lab\bin\JetBrains\data-idea\system\tomcat\Unnamed_wukong-practice-urule
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20\temp
11-Dec-2017 16:41:58.845 信息 [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.12] using APR version [1.5.2].
11-Dec-2017 16:41:58.846 信息 [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
11-Dec-2017 16:41:58.846 信息 [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
11-Dec-2017 16:41:59.954 信息 [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2k  26 Jan 2017]
11-Dec-2017 16:42:00.360 信息 [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
11-Dec-2017 16:42:00.411 信息 [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
11-Dec-2017 16:42:00.422 信息 [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
11-Dec-2017 16:42:00.432 信息 [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
11-Dec-2017 16:42:00.433 信息 [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2145 ms
11-Dec-2017 16:42:00.493 信息 [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
11-Dec-2017 16:42:00.493 信息 [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.20
11-Dec-2017 16:42:00.552 信息 [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
11-Dec-2017 16:42:00.572 信息 [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
11-Dec-2017 16:42:00.583 信息 [main] org.apache.catalina.startup.Catalina.start Server startup in 149 ms
Connected to server
[2017-12-11 04:42:00,737] Artifact wukong-practice-urule:war exploded: Artifact is being deployed, please wait...
11-Dec-2017 16:42:10.556 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20\webapps\manager]
11-Dec-2017 16:42:10.811 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [D:\Work\bin-java\apache-tomcat\apache-tomcat-8.5.20\webapps\manager] has finished in [254] ms
11-Dec-2017 16:42:14.207 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11-Dec-2017 16:42:14.399 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.web.context.ContextLoader.initWebApplicationContext Root WebApplicationContext: initialization started
11-Dec-2017 16:42:15.172 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.context.support.AbstractApplicationContext.prepareRefresh Refreshing Root WebApplicationContext: startup date [Mon Dec 11 16:42:15 CST 2017]; root of context hierarchy
11-Dec-2017 16:42:15.914 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions Loading XML bean definitions from file [D:\Work\Lab\ws-wukong\wukong-practice-urule\target\wkp-urule-0.0.1\WEB-INF\classes\spring-context-urule.xml]
11-Dec-2017 16:42:16.257 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions Loading XML bean definitions from class path resource [urule-console-context.xml]
11-Dec-2017 16:42:16.308 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions Loading XML bean definitions from class path resource [urule-core-context.xml]
11-Dec-2017 16:42:17.863 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties Loading properties file from class path resource [urule-conf.properties]
11-Dec-2017 16:42:17.881 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties Loading properties file from class path resource [urule-core-context.properties]
11-Dec-2017 16:42:17.885 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties Loading properties file from class path resource [urule-console-context.properties]
Load built in actions...
11-Dec-2017 16:42:18.381 信息 [RMI TCP Connection(3)-127.0.0.1] com.bstek.urule.console.repository.RepositoryBuilder.initRepositoryDir Use "D:/tmp/urule" as urule repository home directory.
11-Dec-2017 16:42:19.023 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.RepositoryImpl.<init> Starting repository...
11-Dec-2017 16:42:19.032 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.fs.local.LocalFileSystem.init LocalFileSystem initialized at path D:\tmp\urule\repository
11-Dec-2017 16:42:19.458 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.nodetype.NodeTypeRegistry.loadCustomNodeTypeDefs no custom node type definitions found
11-Dec-2017 16:42:19.579 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.fs.local.LocalFileSystem.init LocalFileSystem initialized at path D:\tmp\urule\version
11-Dec-2017 16:42:19.662 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.fs.local.LocalFileSystem.init LocalFileSystem initialized at path D:\tmp\urule\version\blobs
11-Dec-2017 16:42:20.084 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.RepositoryImpl$WorkspaceInfo.initialize initializing workspace 'default'...
11-Dec-2017 16:42:20.085 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.fs.local.LocalFileSystem.init LocalFileSystem initialized at path D:\tmp\urule\workspaces\default
11-Dec-2017 16:42:20.087 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.fs.local.LocalFileSystem.init LocalFileSystem initialized at path D:\tmp\urule\workspaces\default\blobs
11-Dec-2017 16:42:20.534 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.RepositoryImpl$WorkspaceInfo.initialize workspace 'default' initialized
11-Dec-2017 16:42:20.587 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.RepositoryImpl.initSecurityManager SecurityManager = class org.apache.jackrabbit.core.security.simple.SimpleSecurityManager
11-Dec-2017 16:42:20.601 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.security.simple.SimpleSecurityManager.init init: using Repository LoginModule configuration for uruleRepoSecurity
11-Dec-2017 16:42:20.629 信息 [RMI TCP Connection(3)-127.0.0.1] org.apache.jackrabbit.core.RepositoryImpl.<init> Repository started (1606ms)

_____  __________ _____  ________ ________________ 
__  / / /___  __ \__  / / /___  / ___  ____/__|__ \
_  / / / __  /_/ /_  / / / __  /  __  __/   ____/ /
/ /_/ /  _  _, _/ / /_/ /  _  /____  /___   _  __/ 
\____/   /_/ |_|  \____/   /_____//_____/   /____/ 
.....................................................................................................
.  uRule, is a Chinese style rule engine licensed under the Apache License 2.0,                     .
.  which is opensource, easy to use,high-performance, with browser-based-designer.                  .
.....................................................................................................

11-Dec-2017 16:42:22.623 信息 [RMI TCP Connection(3)-127.0.0.1] org.springframework.web.context.ContextLoader.initWebApplicationContext Root WebApplicationContext: initialization completed in 8223 ms
[2017-12-11 04:42:22,698] Artifact wukong-practice-urule:war exploded: Artifact is deployed successfully
[2017-12-11 04:42:22,698] Artifact wukong-practice-urule:war exploded: Deploy took 21,961 milliseconds
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.bstek.urule.console.servlet.BaseServletHandler.invokeMethod(BaseServletHandler.java:38)
	at com.bstek.urule.console.servlet.respackage.PackageServletHandler.execute(PackageServletHandler.java:110)
	at com.bstek.urule.console.servlet.URuleServlet.service(URuleServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.bstek.urule.console.repository.RepositoryServiceImpl.createFile(RepositoryServiceImpl.java:943)
	at com.bstek.urule.console.repository.RepositoryServiceImpl.loadProjectResourcePackages(RepositoryServiceImpl.java:978)
	at com.bstek.urule.console.servlet.respackage.PackageServletHandler.loadPackages(PackageServletHandler.java:125)
	... 34 more

```

**Comment by youseries** [comment]
这个版本加新功能时加出来的BUG，目前 2.1.2中已修复，请更新测试，谢谢。
