### ISSUE TITLE
Remote service and local KnowledgePackageService all unavailable

### ISSUE THREAD

**Issue by wengsheng112** [youseries/urule#145]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：

2.1.7

*  #### 遇到的问题详细描述：
Remote service and local KnowledgePackageService all unavailable.
服务端知识包可以成功推送到客户端
Successfully receive the server side to pushed package:test/test-trade1
客户端在调用service.getKnowledge("test-trade1")报错。
把service也打印出来

*  #### 涉及到的异常信息（完整异常信息）：
信息: Loading XML bean definitions from class path resource [context.xml]
. You are using a trial version : urule-pro-2.1.7,please purchase a commercial license.
xxxxxxxxxxxxorg.springframework.context.support.ClassPathXmlApplicationContext@22927a81: startup date [Fri Sep 06 17:09:48 CST 2019]; root of context hierarchy
com.bstek.urule.runtime.service.KnowledgeServiceImpl@5ae63ade
九月 06, 2019 5:09:48 下午 com.bstek.urule.runtime.service.RemoteServiceImpl getKnowledge
信息: Load knowledgepackage [test-trade1] from remote...
Exception in thread "main" com.bstek.urule.exception.RuleException: Remote service and local KnowledgePackageService all unavailable
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.a(KnowledgeServiceImpl.java:84)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.getKnowledge(KnowledgeServiceImpl.java:49)
	at tt.Invoke.doTest(Invoke.java:35)
	at tt.Test.main(Test.java:21)

*  #### 相关截图：

**Comment by youseries** [comment]
service.getKnowledge("test-trade1")
从代码上来看，调用知识包的格式不对，需要的是项目名+"/"+知识包ID，文档视频中都有详细的介绍，
你这里应该是：service.getKnowledge("test/test-trade1")

**Comment by wengsheng112** [comment]
改成service.getKnowledge("test/test-trade1")也是报同样的错误

**Comment by wengsheng112** [comment]
信息: Load knowledgepackage [test/test-trade1] from remote...
Exception in thread "main" com.bstek.urule.exception.RuleException: Remote service and local KnowledgePackageService all unavailable
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.a(KnowledgeServiceImpl.java:84)
	at com.bstek.urule.runtime.service.KnowledgeServiceImpl.getKnowledge(KnowledgeServiceImpl.java:49)
	at tt.Invoke.doTest(Invoke.java:35)
	at tt.Test.main(Test.java:21)

**Comment by youseries** [comment]
urule.resporityServerUrl这个属性配置了没，对于客户端来说，在请求知识包时如果服务端没有推送目标知识包过来，那么它会尝试用urule.resporityServerUrl属性到服务端取知识包，如果有则直接采用本地的。

**Comment by wengsheng112** [comment]
配置服务端的地址，并测试服务端“urule/dynamic/checkLatestJarsDir”和“urule/dynamic/loadDynamicJars”都可以访问。客户端也配置存放的目录D:/repo。因为服务端能推送知识包到客户端，并在客户端有显示成功接收到知识包。urule.knowledgeUpdateCycle这个0和1都试过了。也debug了，从本地库里面没有找到该文件后去服务端拉取知识包也没有拉取成功

**Comment by youseries** [comment]
客户端不能配置存放的目录D:/repo，否则引擎会尝试在客户端找这个知识包。所以这个属性置为空，配置好urule.resporityServerUrl属性即可。
