### ISSUE TITLE
前端urule-console-js无法编译，提示缺少./src/client/index.jsx

### ISSUE THREAD

**Issue by FrogLong** [youseries/urule#155]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：2.1.7

*  #### 遇到的问题详细描述：使用webpack编译urule-console-js源码时，编译失败，异常信息请参考如下：

*  #### 涉及到的异常信息（完整异常信息）：
问题关键应该是这儿： ERROR in Entry module not found: Error: Can't resolve './src/client/index.jsx' in 'E:\sourcecode\urule-master\urule-console-js1'；
我在项目包中未找到/src/client/index.jsx文件，请问如何解决，谢谢！

完整异常信息如下：
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 60879cda3623e4fb2764
Version: webpack 4.41.6
Time: 431ms
Built at: 2020-02-25 12:00:44
                              Asset      Size                     Chunks             Chunk Names
             actionEditor.bundle.js  5.75 KiB               actionEditor  [emitted]  actionEditor
           constantEditor.bundle.js  5.76 KiB             constantEditor  [emitted]  constantEditor
      decisionTableEditor.bundle.js  5.85 KiB        decisionTableEditor  [emitted]  decisionTableEditor
       decisionTreeEditor.bundle.js  5.85 KiB         decisionTreeEditor  [emitted]  decisionTreeEditor
             flowDesigner.bundle.js  5.74 KiB               flowDesigner  [emitted]  flowDesigner
                    frame.bundle.js  5.74 KiB                      frame  [emitted]  frame
            packageEditor.bundle.js  5.76 KiB              packageEditor  [emitted]  packageEditor
          parameterEditor.bundle.js  5.77 KiB            parameterEditor  [emitted]  parameterEditor
   permissionConfigEditor.bundle.js  5.78 KiB     permissionConfigEditor  [emitted]  permissionConfigEditor
            ruleSetEditor.bundle.js   5.8 KiB              ruleSetEditor  [emitted]  ruleSetEditor
           scoreCardTable.bundle.js  5.77 KiB             scoreCardTable  [emitted]  scoreCardTable
scriptDecisionTableEditor.bundle.js  5.89 KiB  scriptDecisionTableEditor  [emitted]  scriptDecisionTableEditor
                 ulEditor.bundle.js  5.78 KiB                   ulEditor  [emitted]  ulEditor
           variableEditor.bundle.js  5.76 KiB             variableEditor  [emitted]  variableEditor
Entrypoint frame = frame.bundle.js
Entrypoint variableEditor = variableEditor.bundle.js
Entrypoint constantEditor = constantEditor.bundle.js
Entrypoint parameterEditor = parameterEditor.bundle.js
Entrypoint actionEditor = actionEditor.bundle.js
Entrypoint packageEditor = packageEditor.bundle.js
Entrypoint flowDesigner = flowDesigner.bundle.js
Entrypoint ruleSetEditor = ruleSetEditor.bundle.js
Entrypoint decisionTableEditor = decisionTableEditor.bundle.js
Entrypoint scriptDecisionTableEditor = scriptDecisionTableEditor.bundle.js
Entrypoint decisionTreeEditor = decisionTreeEditor.bundle.js
Entrypoint ulEditor = ulEditor.bundle.js
Entrypoint scoreCardTable = scoreCardTable.bundle.js
Entrypoint permissionConfigEditor = permissionConfigEditor.bundle.js
[./src/action/index.jsx] 1.72 KiB {actionEditor} [built] [failed] [1 error]
[./src/constant/index.jsx] 1.72 KiB {constantEditor} [built] [failed] [1 error]
[./src/editor/decisiontable/index.jsx] 1.73 KiB {decisionTableEditor} [built] [failed] [1 error]
[./src/editor/decisiontree/index.jsx] 1.73 KiB {decisionTreeEditor} [built] [failed] [1 error]
[./src/editor/scriptdecisiontable/index.jsx] 1.74 KiB {scriptDecisionTableEditor} [built] [failed] [1 error]
[./src/editor/ul/index.jsx] 1.72 KiB {ulEditor} [built] [failed] [1 error]
[./src/editor/urule/index.jsx] 1.73 KiB {ruleSetEditor} [built] [failed] [1 error]
[./src/flow/index.jsx] 1.71 KiB {flowDesigner} [built] [failed] [1 error]
[./src/frame/index.jsx] 1.72 KiB {frame} [built] [failed] [1 error]
[./src/package/index.jsx] 1.72 KiB {packageEditor} [built] [failed] [1 error]
[./src/parameter/index.jsx] 1.72 KiB {parameterEditor} [built] [failed] [1 error]
[./src/permission/index.jsx] 1.72 KiB {permissionConfigEditor} [built] [failed] [1 error]
[./src/scorecard/index.jsx] 1.72 KiB {scoreCardTable} [built] [failed] [1 error]
[./src/variable/index.jsx] 1.72 KiB {variableEditor} [built] [failed] [1 error]

ERROR in Entry module not found: Error: Can't resolve './src/client/index.jsx' in 'E:\sourcecode\urule-master\urule-console-js1'

ERROR in ./src/action/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\action"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/constant/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\constant"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/editor/decisiontable/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\editor\\decisiontable"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/editor/decisiontree/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\editor\\decisiontree"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/editor/scriptdecisiontable/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\editor\\scriptdecisiontable"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/editor/ul/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\editor\\ul"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/editor/urule/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\editor\\urule"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/flow/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\flow"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/frame/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\frame"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/package/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\package"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/parameter/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\parameter"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/permission/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\permission"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/scorecard/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\scorecard"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)

ERROR in ./src/variable/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "react" relative to directory "E:\\sourcecode\\urule-master\\urule-console-js1\\src\\variable"
    at E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\sourcecode\urule-master\urule-console-js1\node_modules\babel-loader\lib\index.js:173:20)
*  #### 相关截图：

**Comment by yangyining** [comment]
亲测建一个空文件可以编译通过。

**Comment by FrogLong** [comment]
> 亲测建一个空文件可以编译通过。

那前端可以正常访问吗？

**Comment by shaoyn** [comment]
看下git提交历史记录里面有，后面估计让作者给误删了，有点坑

**Comment by caojiahui123** [comment]
请问前端有可以本地启动的指令配置吗？
