### ISSUE TITLE
添加向导式决策集并对该决策集进行快速测试时，提示服务端错误Class not exist.

### ISSUE THREAD

**Issue by ArthurHou** [youseries/urule#172]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
3.0.1

*  #### 遇到的问题详细描述：
在项目中新建了向导式规则集，然后对该规则集进行快速测试时，提示 com.bstek.urule.exception.RuleException: Class [com.ah.entity.DecisionInfo] not exist. 

*  #### 涉及到的异常信息（完整异常信息）：
错误发生位置：执行规则[rule01(jcr:/demo/demoRule.rs.xml)]动作>>动作1.变量赋值
com.bstek.urule.exception.RuleException: Class [com.ah.entity.DecisionInfo] not exist.
	at com.bstek.urule.action.VariableAssignAction.execute(VariableAssignAction.java:57)
	at com.bstek.urule.runtime.agenda.ActivationImpl.a(ActivationImpl.java:87)
	at com.bstek.urule.runtime.agenda.ActivationImpl.execute(ActivationImpl.java:63)
	at com.bstek.urule.runtime.agenda.ActivationRuleBox.execute(ActivationRuleBox.java:41)

*  #### 相关截图：

**Comment by ArthurHou** [comment]
已经解决了， 谢谢。

**Comment by GuiQuLaiXiCi** [comment]
你好，我也遇到这个问题了，添加决策集并对该决策进行快速测试时，给变量赋值时报错Class not exist。请问这个问题该怎么解决，谢谢！

**Comment by GuiQuLaiXiCi** [comment]
您好，请问这个问题您是怎么解决的？我也遇到了这个问题，给变量赋值的时候，快速测试时报这个错误。谢谢您的回答。

**Comment by Askerlve** [comment]
变量库是有类的类型的，应该是配置跟实际代码对应不上导致，可以在查看源码那里确认源代码中是否包含这个类。
@GuiQuLaiXiCi
