### ISSUE TITLE
URULE中使用求和函数报 Not support reference type

### ISSUE THREAD

**Issue by skybow11** [youseries/urule#49]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的URule的具体版本号：
2.1.5

*  #### 遇到的问题详细描述：
编辑规则的时候，可以保存。但是再次打开就会报上述错误。
看了一下似乎使用“函数”功能就会报这个错误。阅读源码发现是leftParser这个类里面的parse方法里面的一个switch语句。在commonfunction这个分支之后没有加break。
请问是有意这样写还是一时疏忽？望解答。谢谢。

*  #### 涉及到的异常信息（完整异常信息）：
com.bstek.urule.RuleException: Not support reference type.
	at com.bstek.urule.parse.LeftParser.parse(LeftParser.java:63)
	at com.bstek.urule.parse.CriteriaParser.parse(CriteriaParser.java:44)
	at com.bstek.urule.parse.CriteriaParser.parse(CriteriaParser.java:28)
	at com.bstek.urule.parse.CriterionParser.parseCriterion(CriterionParser.java:46)
	at com.bstek.urule.parse.JunctionParser.parse(JunctionParser.java:31)
	at com.bstek.urule.parse.JunctionParser.parse(JunctionParser.java:29)
	at com.bstek.urule.parse.LhsParser.parseCriterion(LhsParser.java:50)
	at com.bstek.urule.parse.LhsParser.parse(LhsParser.java:36)
	at com.bstek.urule.parse.AbstractRuleParser.parseRule(AbstractRuleParser.java:84)
	at com.bstek.urule.parse.RuleParser.parse(RuleParser.java:29)
	at com.bstek.urule.parse.RuleSetParser.parse(RuleSetParser.java:55)
	at com.bstek.urule.parse.deserializer.RuleSetDeserializer.deserialize(RuleSetDeserializer.java:31)
	at com.bstek.urule.parse.deserializer.RuleSetDeserializer.deserialize(RuleSetDeserializer.java:27)
	at com.bstek.urule.console.servlet.common.CommonServletHandler.loadXml(CommonServletHandler.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.bstek.urule.console.servlet.BaseServletHandler.invokeMethod(BaseServletHandler.java:38)
	at com.bstek.urule.console.servlet.common.CommonServletHandler.execute(CommonServletHandler.java:79)
	at com.bstek.urule.console.servlet.URuleServlet.service(URuleServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:84)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at cn.ffcs.bigdata.base.filter.LoginFilter.doFilter(LoginFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.jasig.cas.client.util.AssertionThreadLocalFilter.doFilter(AssertionThreadLocalFilter.java:54)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at cn.ffcs.bigdata.base.filter.CasAuthenticationFilter.doFilter(CasAuthenticationFilter.java:79)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:76)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

*  #### 相关截图：

**Comment by skybow11** [comment]
补上截图
![image](https://user-images.githubusercontent.com/28858677/34699673-ab9929d0-f519-11e7-9c0a-229da09b4cbe.png)

**Comment by youseries** [comment]
看起来是你加了一个命名联合条件，这个功能下个版本就会被取消，所以请不要再使用此功能，如果用了请删除，谢谢。

**Comment by skybow11** [comment]
我并没有使用命名联合条件。而是在条件里面使用了函数。具体结构如下图。是不是在if里面不能使用函数呢？
![image](https://user-images.githubusercontent.com/28858677/34707240-59b8d13c-f547-11e7-8f4f-99cbd8dc62ca.png)

**Comment by youseries** [comment]
已确认是少加了break，最新的2.1.5-SNAPSHOT中已添加，请更新测试，谢谢。

**Comment by skybow11** [comment]
已经测试通过，谢谢！
